### ISSUE TITLE
Load initial data throws error

### ISSUE THREAD

**Issue by glind** [buildlyio/buildly-core#328]
# Bug report
When deploying a new instance the initial data script fails.

Mon Sep 14 22:47:13 UTC 2020 - Load Initial Data
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/code/buildly/management/commands/loadinitialdata.py", line 92, in handle
    self._create_oauth_application()
  File "/code/buildly/management/commands/loadinitialdata.py", line 33, in _create_oauth_application
    if settings.OAUTH_CLIENT_ID and settings.OAUTH_CLIENT_SECRET:
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 80, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'OAUTH_CLIENT_ID'
## Current behavior
Deploy on a new cluster/instance fails with 502 gateway error

## Expected behavior
Deploy works with database

## Enviroment
Buildly version : x.y.z
Logs: ``

**Comment by jefmoura** [comment]
As we can see in the configuration tables https://github.com/buildlyio/buildly-core#configuration we have `OAUTH_CLIENT_ID` and `OAUTH_CLIENT_SECRET` to be set. Maybe we should be clearer saying it's required 'cause if they aren't set, the authentication system won't work; consequently users won't be able to access any endpoint.
